import type { ExportedHandler, ScheduledController } from "@cloudflare/workers-types";

import { syncMeshcoreRepeaters } from "./lib/server/meshcore/repeaters";

// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: CloudflareEnv) {
    try {
      const result = await syncMeshcoreRepeaters(env.DB);
      console.info("MeshCore CoreScope repeater sync completed", result);
    } catch (error) {
      console.error("MeshCore CoreScope repeater sync failed", error);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
