import type { ExportedHandler, ScheduledController } from "@cloudflare/workers-types";

import { runMeshcoreRepeaterSyncJob } from "./lib/server/meshcore/repeaters";

export { GeocodeCoordinator } from "./lib/server/geocode/coordinator";

// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: CloudflareEnv) {
    await runMeshcoreRepeaterSyncJob(env.DB);
  },
} satisfies ExportedHandler<CloudflareEnv>;
