import type { ExportedHandler, ScheduledController } from "@cloudflare/workers-types";

import { syncMeshcoreRepeaters } from "./lib/server/meshcore/repeaters";

// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: CloudflareEnv) {
    const result = await syncMeshcoreRepeaters(env.DB);
    const failedRegions = result.regions.filter((region) => region.error);

    if (failedRegions.length > 0) {
      console.error("MeshCore repeater sync completed with errors", failedRegions);
    } else {
      console.info("MeshCore repeater sync completed", result);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
